const WEATHER = 'WEATHER'
const MONEY_EXCHANGE = 'MONEY_EXCHANGE'
const SAVE_NOTE = 'SAVE_NOTE'
const SHOW_NOTE = 'SHOW_NOTE'
const DELETE_NOTE = 'DELETE_NOTE'
const SHOW_NOTE_LIST = 'SHOW_NOTE_LIST'
const ADVICE = 'ADVICE'
const QUOTE = 'QUOTE'

module.exports = { 
  ADVICE, 
  QUOTE,
  WEATHER,
  SAVE_NOTE, 
  SHOW_NOTE, 
  DELETE_NOTE,
  SHOW_NOTE_LIST, 
  MONEY_EXCHANGE, 
}
